// <auto-generated />
namespace Loja.Repositorios.SqlServer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProdutoImagem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProdutoImagem));
        
        string IMigrationMetadata.Id
        {
            get { return "201709301346520_ProdutoImagem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
